server:
  port: 8080


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/fourseason?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: DECADEMO


mybatis:
  type-aliases-package: com.decademo.fourseason01.entities    # 所有Entity别名类所在包